### ISSUE TITLE
GitHubの使い方

### ISSUE THREAD

**Issue by yasunari** [softlondon/softtennis#1]
> ここまでできたんだけどこの先どうすればいい?

ここで議論しませんか。

**Comment by softlondon** [comment]
お願いします
スレッドっていうのかな(？)は建てられたのですがそれにコードを追加する方法がわからず苦しんでいるのですが助けて頂けますでしょうか？

**Comment by yasunari** [comment]
CodeをGitHubに上げる方法については，環境によって異なりますので，Googleで調べてみて下さい。詳細な[Pro Git](https://git-scm.com/book/ja/v2)というManualは持っておくと便利です。

GitHub上でHomepageを公開するとなるとGitHub Pagesを利用することになるでしょうが，Repository名に制約がかかります。今のAccountですと`softlondon.github.io`にする必要がありますが，軟テ公式にするなら新しいOrganizationを作った方が，URLになることを考えると良いでしょう。

ちなみに，私は湯河原におりますので直ぐに応答できる環境ではありません。

![43850767-cebc4162-9b73-11e8-8eac-1337b46c8220](https://user-images.githubusercontent.com/38091102/44157774-35331180-a0ee-11e8-8c9d-694d1fa86576.JPG)

**Comment by softlondon** [comment]
あ、囲碁部の合宿ですか。頑張って下さい。こちらも少し頑張って見ます。

**Comment by yasunari** [comment]
東京に帰っています。WindowsのCUIがどのようになっているかは存じあげませんが，何らかの方法でRepositoryをCloneすることになるでしょう。英語が得意ならば，

* [GitHub Guides](https://guides.github.com)
* [GitHub Help](https://help.github.com)
* [GitHub Pages](https://pages.github.com)

といった公式の説明書も読んでみては，いかがでしょう。GitHubによるGUIは以下になります。

* [GitHub Desktop](https://desktop.github.com)
* [GitHub Desktop Documentation](https://help.github.com/desktop/)

**Comment by yasunari** [comment]
閉じておきますね。
